apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-argocd-demo
  namespace: argocd
spec:
  source:
    path: manifests
#   repoURL: 'https://github.com/rotemtam/atlas-argocd-demo'
    repoURL: 'https://github.com/Blackboxops1/argocd-seq-rollout-template-template-v1'
    targetRevision: master
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
    namespace: bbsignup
  project: Bbapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true